version: '3.8'

services:
  api:
    build: .
    container_name: elo-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8000
      - DB_URL=jdbc:postgresql://db:5432/elo-bd
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: cardial-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=elo-bd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123mudar
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d elo-bd"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
