spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elo_db
    username: ${DB_USER}
    password: ${DB_PASS}
  
  mail:
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}

jwt:
  secret: ${JWT_SECRET}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  bucket-name: ${AWS_BUCKET_NAME}